arb-dir: lib/l10n/src
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: .dart_tool/flutter_gen/gen_l10n/desiredFileName.txt
nullable-getter: false