name: money_tracker

# Пути, где Melos будет искать пакеты и приложения
packages:
  - apps/**
  - packages/**

# Команды для автоматизации
scripts:
  # Установка всех зависимостей во всех пакетах одной командой
  get:
    run: melos bootstrap
    description: "Install all dependencies and link packages"

  # Очистка всех проектов (аналог flutter clean для всего репо)
  clean:
    run: melos exec -- "flutter clean"
    description: "Run flutter clean in all apps"

  # Запуск генерации кода (Drift, JSON) во всех пакетах сразу
  build:
    run: melos exec -- "dart run build_runner build --delete-conflicting-outputs"
    description: "Run build_runner in all packages"

  test:
    run: melos exec --dir-exists=test -- "flutter test"
    description: "Run all tests"

  test:coverage:
    run: melos exec --scope="money_tracker" --dir-exists=test -- "flutter test --coverage"
    description: "Run coverage for mobile app"

  coverage:report:
    run: powershell -ExecutionPolicy Bypass -File tool/generate_coverage_report.ps1 -LcovPath "apps/mobile/coverage/lcov.info" -OutputDir "apps/mobile/coverage/html"
    description: "Generate HTML coverage report"

  test:coverage:report:
    run: |
      melos exec --scope="money_tracker" --dir-exists=test -- "flutter test --coverage"
      powershell -ExecutionPolicy Bypass -File tool/generate_coverage_report.ps1 -LcovPath "apps/mobile/coverage/lcov.info" -OutputDir "apps/mobile/coverage/html"
    description: "Run coverage and generate HTML report for mobile app"


  server:dir:
    run: cd apps/server && dart_frog dev
    description: "Запуск через переход в директорию"

  db:start:
    run: docker-compose up -d
    description: "Запустить базу данных Postgres"

  db:stop:
    run: docker-compose down
    description: "Остановить базу данных"

  server:start:
    run: |
      melos run db:start
      melos bootstrap
      melos server:dir
    description: "Запуск Postgres, привязка пакетов и старт сервера с Hot Reload"

  server:stop:
    run: |
      melos run db:stop
      melos exec --scope="backend" -- "pkill -f dart_frog" || true
    description: "Остановка Docker-контейнеров и завершение процессов Dart Frog"
