name: money_tracker
description: A new Flutter application.

version: 1.1.13+25

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  provider: ^6.0.1

  drift: ^1.1.0
  sqlite3_flutter_libs: ^0.5.2
  path_provider: ^2.0.8
  path: ^1.8.0

  intl: ^0.17.0
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  bloc_test: ^9.0.1

  scrollable_positioned_list: ^ 0.2.0-nullsafety.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.4

  charts_flutter: ^0.12.0

  firebase_core: ^1.10.5
  cloud_firestore: ^3.1.4
  firebase_auth: ^3.3.3
  firebase_crashlytics: ^2.4.3

  shared_preferences: ^2.0.11

  connectivity_plus: ^2.1.0

  mocktail: ^0.2.0
  equatable: ^2.0.3

  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.1.0
  build_runner:
  pedantic: ^1.11.1
  googleapis: any
  googleapis_auth: any
  google_sign_in: ^5.2.1
#  test: ^1.19.3

flutter:

  uses-material-design: true