name: money_tracker
description: A new Flutter application.

version: 1.1.16+28

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  provider: ^6.0.2

  drift: ^1.2.0
  sqlite3_flutter_libs: ^0.5.3
  path_provider: ^2.0.8
  path: ^1.8.0

  intl: ^0.17.0
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
#  bloc_test: ^9.0.2

  scrollable_positioned_list: ^ 0.2.0-nullsafety.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.4

  charts_flutter: ^0.12.0
  horizontal_data_table: ^3.6.0

  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_crashlytics: ^2.4.5

  shared_preferences: ^2.0.12

  connectivity_plus: ^2.2.0

  mockito: ^5.1.0
  equatable: ^2.0.3

  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.2.1
  build_runner:
  pedantic: ^1.11.1
  googleapis: any
  googleapis_auth: any
  google_sign_in: ^5.2.2
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.13.0
#  test: ^1.19.3

flutter:

  uses-material-design: true