name: money_tracker
description: A new Flutter application.

version: 1.1.31+41

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  get_it: ^7.2.0

  go_router: ^6.0.1

  drift: ^2.3.0
  sqlite3_flutter_libs: ^0.5.7
  path_provider: ^2.0.11
  path: ^1.8.1

  intl: ^0.17.0
  flutter_bloc: ^8.1.1
#  bloc_test: ^9.0.2

  scrollable_positioned_list: ^0.3.2

#  charts_flutter: ^0.12.0
  horizontal_data_table: ^4.1.4

  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_crashlytics: ^3.0.11

  googleapis: ^10.0.0
  googleapis_auth: ^1.3.1
  google_sign_in: ^5.4.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.7

  shared_preferences: ^2.0.17

  connectivity_plus: ^3.0.2

  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0

  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.3.2
  build_runner:
  pedantic: ^1.11.1
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.5.0
  freezed: ^2.3.2
#  test: ^1.19.3
  mockito: ^5.2.0

flutter:
  generate: true
  uses-material-design: true