name: money_tracker
description: A new Flutter application.

version: 1.1.38+48

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  get_it: ^7.6.4

  go_router: ^10.1.2

  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.16
  path_provider: ^2.0.12
  path: ^1.8.1

  intl: ^0.18.1
  flutter_bloc: ^8.1.3
#  bloc_test: ^9.0.2

  scrollable_positioned_list: ^0.3.8

#  charts_flutter: ^0.12.0
  horizontal_data_table: ^4.3.1

  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  firebase_crashlytics: ^3.3.5

  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  google_sign_in: ^6.1.5
  extension_google_sign_in_as_googleapis_auth: ^2.0.11

  shared_preferences: ^2.2.1

  connectivity_plus: ^4.0.2

  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0

  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.11.1
  build_runner:
  pedantic: ^1.11.1
  flutter_lints: ^2.0.3
  dart_code_metrics: ^5.7.6
  freezed: ^2.3.2
#  test: ^1.19.3
  mockito: ^5.4.2

flutter:
  generate: true
  uses-material-design: true