name: money_tracker
description: A new Flutter application.

version: 1.1.30+40

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.3

  get_it: ^7.2.0

  drift: ^1.7.0
  sqlite3_flutter_libs: ^0.5.7
  path_provider: ^2.0.11
  path: ^1.8.1

  intl: ^0.17.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
#  bloc_test: ^9.0.2

  scrollable_positioned_list: ^0.3.2

#  charts_flutter: ^0.12.0
  horizontal_data_table: ^4.1.1

  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  firebase_crashlytics: ^2.8.2

  googleapis: ^9.1.0
  googleapis_auth: ^1.3.1
  google_sign_in: ^5.3.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.5

  shared_preferences: ^2.0.15

  connectivity_plus: ^2.3.5

  mockito: ^5.2.0
  equatable: ^2.0.3

  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.7.0
  build_runner:
  pedantic: ^1.11.1
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.16.0
#  test: ^1.19.3

flutter:

  uses-material-design: true