name: money_tracker
description: A new Flutter application.

version: 1.0.1+10

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  provider: ^5.0.0

  moor: ^4.3.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider:
  path:

  intl: ^0.17.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  firebase_crashlytics: ^2.2.0
  scrollable_positioned_list: ^ 0.2.0-nullsafety.0

  charts_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.3.1
  build_runner:
  pedantic: ^1.11.1
  googleapis: any
  googleapis_auth: any
  google_sign_in: ^5.0.4

  path_provider: ^2.0.2
  shared_preferences: ^2.0.6

flutter:

  uses-material-design: true