name: money_tracker
description: A new Flutter application.

version: 1.0.1+12

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  provider: ^6.0.1

  moor: ^4.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider:
  path:

  intl: ^0.17.0
  bloc: ^7.2.0
  flutter_bloc: ^7.3.0
  firebase_crashlytics: ^2.2.1
  scrollable_positioned_list: ^ 0.2.0-nullsafety.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.3

  charts_flutter: ^0.11.0

  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.5.1
  build_runner:
  pedantic: ^1.11.1
  googleapis: any
  googleapis_auth: any
  google_sign_in: ^5.1.1

  shared_preferences: ^2.0.8

flutter:

  uses-material-design: true