name: money_tracker
description: A new Flutter application.

version: 1.1.14+26

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.0.5

  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.17
  path_provider: ^2.1.1
  path: ^1.8.3

  intl: ^0.18.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.4

  scrollable_positioned_list: ^ 0.2.0-nullsafety.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.11

  horizontal_data_table: ^4.3.1

  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  firebase_crashlytics: ^3.3.5

  shared_preferences: ^2.2.1

  connectivity_plus: ^4.0.2

  mocktail: ^1.0.0
  equatable: ^2.0.5

  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0

  file: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.11.2
  build_runner:
  pedantic: ^1.11.1
  googleapis: any
  googleapis_auth: any
  google_sign_in: ^6.1.5
#  test: ^1.19.3

flutter:

  uses-material-design: true