// Mocks generated by Mockito 5.4.6 from annotations
// in money_tracker/test/domain/interactors/account_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:money_tracker/src/domain/interfaces/account_repository.dart'
    as _i2;
import 'package:money_tracker/src/domain/models.dart' as _i4;
import 'package:money_tracker/src/domain/services/balance_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i2.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.BaseAccount>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i3.Stream<List<_i4.BaseAccount>>.empty(),
          )
          as _i3.Stream<List<_i4.BaseAccount>>);

  @override
  _i3.Future<List<_i4.BaseAccount>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<List<_i4.BaseAccount>>.value(
              <_i4.BaseAccount>[],
            ),
          )
          as _i3.Future<List<_i4.BaseAccount>>);

  @override
  _i3.Stream<_i4.BaseAccount> watchById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchById, [id]),
            returnValue: _i3.Stream<_i4.BaseAccount>.empty(),
          )
          as _i3.Stream<_i4.BaseAccount>);

  @override
  _i3.Future<_i4.BaseAccount> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i4.BaseAccount>.value(
              _i5.dummyValue<_i4.BaseAccount>(
                this,
                Invocation.method(#getById, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseAccount>);

  @override
  _i3.Future<int> insert(_i4.BaseAccount? account) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [account]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> update(_i4.BaseAccount? account) =>
      (super.noSuchMethod(
            Invocation.method(#update, [account]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [BalanceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBalanceService extends _i1.Mock implements _i6.BalanceService {
  MockBalanceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.AccountBalanceItem>> watchAllBalance() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllBalance, []),
            returnValue: _i3.Stream<List<_i4.AccountBalanceItem>>.empty(),
          )
          as _i3.Stream<List<_i4.AccountBalanceItem>>);

  @override
  _i3.Future<List<_i4.AccountBalanceItem>> getAllBalance() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBalance, []),
            returnValue: _i3.Future<List<_i4.AccountBalanceItem>>.value(
              <_i4.AccountBalanceItem>[],
            ),
          )
          as _i3.Future<List<_i4.AccountBalanceItem>>);
}
