name: finance_api_client
resolution: workspace

description: "A new Flutter package project."
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0

  finance_models: any
  dto_models: any

  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  uuid: ^4.5.3
  dio: ^5.9.2
  retrofit: ^4.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.13.1
  freezed: ^3.2.5
  json_serializable: ^6.13.1
  retrofit_generator: ^10.2.3

flutter:


